### ISSUE TITLE
qfit_protein crashes very quickly with cryoEM maps

### ISSUE THREAD

**Issue by blake-riley** [ExcitedStates/qfit-3.0#105]
As soon as qfit_protein is sending jobs (and objects) to PoolWorkers, it crashes.

The traceback is quite useful. Other people who have encountered similar MemoryError / struct.error suggest that the pickler is trying to send a >2GB (maxsize) object. It is worth noting that the mapfile is only 17580 kB, however—a far cry from 2GB.

1. Rather than loading maps in the MainProcess and passing the object to the worker, we should tell workers to load the map themselves.
2. Is the size of the map object hinting at an error in the ccp4 reader? (I hope not).

**Comment by blake-riley** [comment]
```
2020-08-04 13:01:52,174 [INFO    ] MainProcess qfit.qfit_protein : /wynton/home/fraserlab/swankowicz/anaconda3/envs/qfit3_EM/bin/qfit_protein map_box.ccp4 model_box.pdb -p 1 -r 1.6 -z electron -v --debug

...

2020-08-04 13:01:59,594 [INFO    ] MainProcess qfit.qfit_protein : RESIDUES: 2360
2020-08-04 13:01:59,595 [INFO    ] MainProcess qfit.qfit_protein : NPROC: 1
2020-08-04 13:02:04,259 [CRITICAL] MainProcess qfit.qfit_protein : Traceback (most recent call last):
  File "/wynton/home/fraserlab/swankowicz/anaconda3/envs/qfit3_EM/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/wynton/home/fraserlab/swankowicz/anaconda3/envs/qfit3_EM/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/wynton/home/fraserlab/swankowicz/anaconda3/envs/qfit3_EM/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

2020-08-04 13:02:06,897 [CRITICAL] MainProcess qfit.qfit_protein : Traceback (most recent call last):
  File "/wynton/home/fraserlab/swankowicz/anaconda3/envs/qfit3_EM/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/wynton/home/fraserlab/swankowicz/anaconda3/envs/qfit3_EM/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/wynton/home/fraserlab/swankowicz/anaconda3/envs/qfit3_EM/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError
```

**Comment by stephaniewankowicz** [comment]
This is a duplicate issue with #139 which is being dealt with in pull request #176
