### ISSUE TITLE
qfit_residue.py not working 

### ISSUE THREAD

**Issue by ss199514** [ExcitedStates/qfit-3.0#258]
qfit_residue.py line 274 is qfit.write_maps(). We don't write maps in qfit_residue and this is causing it to crash with an error. Commenting out this line solves the issue and qfit_residue runs without error, but the output is incorrect. To replicate the issue:
qfit_residue /path/to/3K0N.mtz -l 2FOFCWT,PH2FOFCWT /path/to/3K0N_refine.pdb A,113
This gives an output with 2f0-fc density unmodeled, the alt conf that are outputted do not satisfy the density and are mostly redundant with the already existing conformation.

**Comment by ashrayar** [comment]
Following is the error output without making any edits to qfit_residue:
```
Beginning qfit_residue
Traceback (most recent call last):
  File "/Users/ashraya/opt/anaconda3/envs/qfit_testing/bin/qfit_residue", line 8, in <module>
    sys.exit(main())
  File "/Users/ashraya/qfit_summit/summit_2/dataset_testing/qfit-3.0/src/qfit/qfit_residue.py", line 274, in main
    qfit.write_maps()
  File "/Users/ashraya/qfit_summit/summit_2/dataset_testing/qfit-3.0/src/qfit/qfit.py", line 405, in write_maps
    self._transformer.xmap.tofile(fname)
  File "/Users/ashraya/qfit_summit/summit_2/dataset_testing/qfit-3.0/src/qfit/volume.py", line 68, in tofile
    to_mrc(fid, self)
  File "/Users/ashraya/qfit_summit/summit_2/dataset_testing/qfit-3.0/src/qfit/volume.py", line 524, in to_mrc
    with open(fid, 'wb') as out:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ashraya/qfit_summit/summit_2/dataset_testing/qfit-3.0/example/A_113/model.ccp4'
```
qfit_residue is trying to output model.ccp4 in A_113 folder but the folder is never created and hence the FileNotFoundError

**Comment by stephaniewankowicz** [comment]
qfit residue is now removed so this is obsolete.
