### ISSUE TITLE
How do I tell qfit_final_refine_xray.sh what are the labels in my mtz file?

### ISSUE THREAD

**Issue by mysecondnameisdanger** [ExcitedStates/qfit-3.0#414]
```
(qfit3) msnid@fedora:~/fin/refine2/final_b2x01/qfit$ qfit_final_refine_xray.sh multiconformer_model2.pdb ../b2x01.mtz 
mapfile              : multiconformer_model2.pdb 
qfit unrefined model : ../b2x01.mtz 

Traceback (most recent call last):
  File "/home/msnid/xstl/phenix-1.21-5207/build/../modules/cctbx_project/iotbx/command_line/mtz.dump.py", line 85, in <module>
    run(args=sys.argv[1:])
  File "/home/msnid/xstl/phenix-1.21-5207/build/../modules/cctbx_project/iotbx/command_line/mtz.dump.py", line 77, in run
    show_batches=command_line.options.show_batches)
  File "/home/msnid/xstl/phenix-1.21-5207/build/../modules/cctbx_project/iotbx/command_line/mtz.dump.py", line 17, in process
    mtz_object = mtz.object(file_name=file_name)
RuntimeError: cctbx Error: MTZ file read error: multiconformer_model2.pdb.mtz

Could not determine Fo field name with corresponding SIGFo in .mtz.
Was not among FP FOBS F-obs I IOBS I-obs F(+) I(+). Please check .mtz file\!
(qfit3) msnid@fedora:~/fin/refine2/final_b2x01/qfit$ qfit_final_refine_xray.sh -h 
mapfile              : -h [NOT FOUND]
qfit unrefined model : multiconformer_model2.pdb 

Usage:
  /home/msnid/anaconda3/envs/qfit3/bin/qfit_final_refine_xray.sh mapfile.mtz [multiconformer_model2.pdb] [qFit_occupancy.params]

mapfile.mtz, multiconformer_model2.pdb, and qFit_occupancy.params MUST exist in this directory.
Outputs will be written to mapfile_qFit.{pdb|mtz|log}.
(qfit3) msnid@fedora:~/fin/refine2/final_b2x01/qfit$ qfit_final_refine_xray.sh --help
mapfile              : --help [NOT FOUND]
qfit unrefined model : multiconformer_model2.pdb 

Usage:
  /home/msnid/anaconda3/envs/qfit3/bin/qfit_final_refine_xray.sh mapfile.mtz [multiconformer_model2.pdb] [qFit_occupancy.params]

mapfile.mtz, multiconformer_model2.pdb, and qFit_occupancy.params MUST exist in this directory.
Outputs will be written to mapfile_qFit.{pdb|mtz|log}.
(qfit3) msnid@fedora:~/fin/refine2/final_b2x01/qfit$ qfit_final_refine_xray.sh
mapfile              :  [NOT FOUND]
qfit unrefined model : multiconformer_model2.pdb 

Usage:
  /home/msnid/anaconda3/envs/qfit3/bin/qfit_final_refine_xray.sh mapfile.mtz [multiconformer_model2.pdb] [qFit_occupancy.params]

mapfile.mtz, multiconformer_model2.pdb, and qFit_occupancy.params MUST exist in this directory.
Outputs will be written to mapfile_qFit.{pdb|mtz|log}.
(qfit3) msnid@fedora:~/fin/refine2/final_b2x01/qfit$ phenix.mtz.dump ../b2x01.mtz 
Processing: ../b2x01.mtz
Title: Converted from INTEGRATE.HKL
Space group symbol from file: P 43 21 2
Space group number from file: 96
Space group from matrices: P 43 21 2 (No. 96)
Point group symbol from file: PG422
Number of crystals: 2
Number of Miller indices: 57297
Resolution range: 55.9088 1.03701
History:
  From FREERFLAG  4/ 4/2024 16:31:22 with fraction 0.050
  From TRUNCATE  4/ 4/2024 16:31:21
  From AIMLESS, version 0.7.15, run on  4/ 4/2024 at 16:30:38
  From gemmi-xds2mtz 0.6.4-dev
  From INTEGRATE (VERSION Jun 30, 2023  BUILT=20230630)
  data from CAD on  4/ 4/24
  data from CAD on  4/ 4/24
Crystal 1:
  Name: HKL_base
  Project: HKL_base
  Id: 1
  Unit cell: (79.067, 79.067, 37.026, 90, 90, 90)
  Number of datasets: 1
  Dataset 1:
    Name: HKL_base
    Id: 0
    Wavelength: 9.999
    Number of columns: 3
    label #valid  %valid  min   max type
    H      57297 100.00% 0.00 76.00 H: index h,k,l
    K      57297 100.00% 0.00 53.00 H: index h,k,l
    L      57297 100.00% 0.00 35.00 H: index h,k,l
Crystal 2:
  Name: A
  Project: Test
  Id: 2
  Unit cell: (79.067, 79.067, 37.026, 90, 90, 90)
  Number of datasets: 1
  Dataset 1:
    Name: 1
    Id: 1
    Wavelength: 1.0332
    Number of columns: 16
    label      #valid  %valid    min      max type
    F           53553  93.47%   2.69  1033.29 F: amplitude
    SIGF        53553  93.47%   0.27    27.11 Q: standard deviation
    IMEAN       53553  93.47%  -2.98 10711.69 J: intensity
    SIGIMEAN    53553  93.47%   0.09   452.00 Q: standard deviation
    DANO        48250  84.21% -82.04   112.33 D: anomalous difference
    SIGDANO     48250  84.21%   0.00    47.30 Q: standard deviation
    ISYM        53553  93.47%   0.00     2.00 Y: M/ISYM, packed partial/reject flag and symmetry number
    I(+)        52931  92.38%  -5.02 10711.69 K: I(+) or I(-)
    SIGI(+)     52931  92.38%   0.09   638.45 M: standard deviation
    I(-)        48872  85.30%  -7.24 10711.69 K: I(+) or I(-)
    SIGI(-)     48872  85.30%   0.09   640.01 M: standard deviation
    F(+)        52931  92.38%   2.69  1033.29 G: F(+) or F(-)
    SIGF(+)     52931  92.38%   0.29    34.03 L: standard deviation
    F(-)        48872  85.30%   2.69  1033.29 G: F(+) or F(-)
    SIGF(-)     48872  85.30%   0.29    32.86 L: standard deviation
    FreeR_flag  57297 100.00%   0.00    19.00 I: integer

(qfit3) msnid@fedora:~/fin/refine2/final_b2x01/qfit$ qfit_final_refine_xray.sh multiconformer_model2.pdb -l F,SIGF ../b2x01.mtz 
mapfile              : multiconformer_model2.pdb 
qfit unrefined model : -l [NOT FOUND]

Usage:
  /home/msnid/anaconda3/envs/qfit3/bin/qfit_final_refine_xray.sh mapfile.mtz [multiconformer_model2.pdb] [qFit_occupancy.params]

mapfile.mtz, multiconformer_model2.pdb, and qFit_occupancy.params MUST exist in this directory.
Outputs will be written to mapfile_qFit.{pdb|mtz|log}.

```

**Comment by stephaniewankowicz** [comment]
Flip your input files around ../b2x01.mtz  multiconformer_model2.pdb and it should work. No need to input your labels.

**Comment by mysecondnameisdanger** [comment]
It starts to run... but then something happens (new issue)

**Comment by stephaniewankowicz** [comment]
Can you attached your phenix refine log file? Also, the command does not take in labels (-l), just the map and mtz. 

You should be running:
qfit_final_refine_xray.sh multiconformer_model2.pdb  ../b2x01.mtz
