### ISSUE TITLE
traceback when running qfit_final_refine_xray.sh

### ISSUE THREAD

**Issue by mysecondnameisdanger** [ExcitedStates/qfit-3.0#415]
```
(qfit3) msnid@fedora:~/fin/refine2/final_b2x01/qfit$ qfit_final_refine_xray.sh ../b2x01.mtz ./multiconformer_model2.pdb 
mapfile              : ../b2x01.mtz 
qfit unrefined model : ./multiconformer_model2.pdb 

Resolution range: 55.9088 1.03701
data labels: I(+),SIGI(+)
Atoms () had earlier, identical atoms.
They are being removed.
normalize_occupancies: 0 atoms had occ < 0.09 and were removed.
0
renamed './multiconformer_model2.pdb.f_norm.pdb' -> './multiconformer_model2.pdb.fixed'
Starting phenix.pdbtools
on Tue Apr  9 08:52:34 2024 by msnid
===============================================================================

Processing files:
-------------------------------------------------------------------------------

  Found model, ./multiconformer_model2.pdb.fixed

Processing PHIL parameters:
-------------------------------------------------------------------------------

  Adding command-line PHIL:
  -------------------------
    remove=element H

Final processed PHIL parameters:
-------------------------------------------------------------------------------
  data_manager {
    model {
      file = "./multiconformer_model2.pdb.fixed"
    }
    default_model = "./multiconformer_model2.pdb.fixed"
  }
  modify {
    remove = element H
  }


Starting job
===============================================================================
Validating inputs
Crystal symmetry undefined, creating fake P1 box.
Performing manipulations
Size before: 3418 size after: 3418
Writing output model

===============================================================================
Job complete
usr+sys time: 1.54 seconds
wall clock time: 1.58 seconds

  INPUT
  
    Reading option "hydrogens=false" from command line
    Reading option "trust_residue_code_is_chemical_components_code=true" from command line
    Reading option "pdb_file_name=./multiconformer_model2.pdb.f_modified.pdb" from command line
    Writing effective parameters to multiconformer_model2.pdb.f_modified.eff

    Ligand restraint generation using eLBOW, phenix.elbow
    
  No unknown residues

  OUTPUT
  
'./multiconformer_model2.pdb.f_modified.pdb' -> './multiconformer_model2.pdb.f_modified.updated.pdb'
Starting phenix.refine
on Tue Apr  9 08:52:41 2024 by msnid
===============================================================================

Processing files:
-------------------------------------------------------------------------------

  Found model, ./multiconformer_model2.pdb.f_modified.updated.pdb
  Found miller_array, ../b2x01.mtz
  Found phil, ../b2x01_refine.params

Processing PHIL parameters:
-------------------------------------------------------------------------------

  Adding PHIL files:
  ------------------
    ../b2x01_refine.params

  Unrecognized PHIL parameters:
  -----------------------------
    refinement.input.xray_data.labels (file "../b2x01_refine.params", line 1)
    refinement.input.xray_data.r_free_flags.generate (file "../b2x01_refine.params", line 2)
    refinement.output.prefix (file "../b2x01_refine.params", line 4)
    refinement.output.serial (file "../b2x01_refine.params", line 5)

Sorry: Some PHIL parameters are not recognized by phenix.refine.
 Please run this program with the --show-defaults option to see what parameters
are available.
 PHIL parameters in files should be fully specified (e.g. "output.overwrite"
instead of just "overwrite")

qfit_final_refine_xray.sh:: Starting refinement round 1...
Starting phenix.refine
on Tue Apr  9 08:52:44 2024 by msnid
===============================================================================

Processing files:
-------------------------------------------------------------------------------

  Found phil, ../b2x01_occ_refine.params
  Found phil, qFit_occupancy.params

Processing PHIL parameters:
-------------------------------------------------------------------------------

  Adding PHIL files:
  ------------------
    ../b2x01_occ_refine.params
    qFit_occupancy.params

  Unrecognized PHIL parameters:
  -----------------------------
    refinement.output.prefix (file "../b2x01_occ_refine.params", line 2)
    refinement.output.serial (file "../b2x01_occ_refine.params", line 3)

Sorry: Some PHIL parameters are not recognized by phenix.refine.
 Please run this program with the --show-defaults option to see what parameters
are available.
 PHIL parameters in files should be fully specified (e.g. "output.overwrite"
instead of just "overwrite")

Traceback (most recent call last):
  File "/home/msnid/anaconda3/envs/qfit3/bin/redistribute_cull_low_occupancies", line 8, in <module>
    sys.exit(main())
  File "/home/msnid/anaconda3/envs/qfit3/lib/python3.9/site-packages/qfit/redistribute_cull_low_occupancies.py", line 219, in main
    structure = Structure.fromfile(args.structure)
  File "/home/msnid/anaconda3/envs/qfit3/lib/python3.9/site-packages/qfit/structure/structure.py", line 30, in fromfile
    pdbfile = PDBFile.read(fname)
  File "/home/msnid/anaconda3/envs/qfit3/lib/python3.9/site-packages/qfit/structure/pdbfile.py", line 50, in read
    with fopen(fname, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../b2x01_003.pdb'
Post refinement zeroes: 
Normalize occupancies did not work!

```

**Comment by mysecondnameisdanger** [comment]
....I think this is because I am using phenix version 1.21. I will try with version 1.20.

**Comment by mysecondnameisdanger** [comment]
Yeah... it was that... some labels/flags/options were changed in between phenix 1.20 and 1.21... I think you can close this issue. Sorry about that.
